version: '2'

services:

  ckan:
    build:
      context: ./
      dockerfile: dockerfile
    image: ckan:dev

  solr:
    build:
      context: ./solr
      dockerfile: dockerfile
    image: ckan-solr:dev
